- name: demo on installing packages
  hosts: local
  connection: local
  become: yes 
  task: 
  - name: install package
    ansible.builtin.package:
     name: {{ item }}
     state: present 
    loop:
    - mysql
    - nginx 
    - zip 




